### ISSUE TITLE
missing sht_temp 

### ISSUE THREAD

**Issue by udgish23** [kimyd/SHT1X_on_nrf51822#1]
sht_temp is missing what is it?

**Comment by kimyd** [comment]
you can get the temperature value from 'sensor_temp'

**Comment by udgish23** [comment]
its undefined where is it define ?

**Comment by kimyd** [comment]
you need to define 4 variables as global in the main.c file.

```
static int sensor_temp;
static int sensor_humid;

static float sensor_temp_f;
static float sensor_humid_f;
```

**Comment by udgish23** [comment]
its give constant zero both  sensor_temp_f and sensor_humid_f I converted code for nrf52

**Comment by kimyd** [comment]
I haven't tested with nrf52.
